### ISSUE TITLE
json.txt.rb outputs invalid json

### ISSUE THREAD

**Issue by lailoken503** [dinoex/iroffer-dinoex#10]
Been trying to write a javascript parser for the packlist, and found that json.txt.rb is not putting out a valid JSON-formatted file.

After a little research and experimentation, I've made some changes to the ruby script to output a file that is JSON friendly, which is attached..

[json.txt](https://github.com/dinoex/iroffer-dinoex/files/3763406/json.txt)

**Comment by dinoex** [comment]
json.txt.rb did generate javscript code, not JSON.

A cleaner approach:
https://github.com/dinoex/iroffer-dinoex/blob/master/htdocs/json.txt.rb
