### ISSUE TITLE
Suppress output if file already exists / add verbosity level

### ISSUE THREAD

**Issue by Moodkiller** [dinoex/iroffer-dinoex#11]
Feature request as it were: Suppress (or add a verbosity level) to reduce the output to the console when iroffer adds files. Would be great to just see the newly added ones instead when autoadd/adddir etc etc is used, or when the bot does its routine scan if configured.

I believe this is this responsible for it: https://github.com/dinoex/iroffer-dinoex/blob/36138cd2e2a9d9c704264a6f42638f64b26fab5d/src/dinoex_admin.c#L1445

**Comment by dinoex** [comment]
The message is only printed when you force add a file.
ADDNEW and AUTOADD shall not generated this message.

Make sure your AUTOADD does not run before the files from previous run are added.

Please check other restrictions in your config  that may be in place.
noduplicatefiles
no_duplicate_filenames

In some cases you like to exclude some cases.
