### ISSUE TITLE
iroffer only responds to server PING when sent with a trailing param

### ISSUE THREAD

**Issue by slingamn** [dinoex/iroffer-dinoex#9]
Hi, and thanks for your project!

I'm one of the maintainers of https://github.com/oragono/oragono, and we got a report that iroffer wasn't interoperating correctly with oragono, specifically that oragono was disconnecting it due to ping timeout. Upon further investigation, the original reporter determined that Oragono was sending lines of the form `PING bot_nickname\r\n`, where `bot_nickname` is the nickname used by the iroffer instance, and iroffer wasn't responding to them.

This appears to be due to a bug in iroffer's message parsing:

https://github.com/dinoex/iroffer-dinoex/blob/61c3b14a8493cb4d971b8723633a416ba42b0f06/src/dinoex_irc.c#L1289

This line assumes that the parameter to PING will be an [RFC1459 trailing parameter](https://tools.ietf.org/html/rfc1459#section-2.3.1), i.e., prefixed with `:`. But in fact this is not a requirement of the protocol, and it is valid for oragono to send `PING bot_nickname\r\n` without the colon.

I haven't tested it, but I think this patch will work:

````diff
diff --git a/src/dinoex_irc.c b/src/dinoex_irc.c
index 5224af25..94d31a70 100644
--- a/src/dinoex_irc.c
+++ b/src/dinoex_irc.c
@@ -1286,7 +1286,7 @@ static void ir_parseline2(ir_parseline_t *ipl)
 
 #if PING_SRVR
   /* server ping */
-  if (strncmp(ipl->line, "PING :", 6) == 0) {
+  if (strncmp(ipl->line, "PING ", 5) == 0) {
     if (gdata.debug > 0)
       ioutput(OUT_S, COLOR_NO_COLOR,
               "Server Ping on %s: %s",
````

Thanks for your time.

**Comment by dinoex** [comment]
Thanks for reporting this.

The updated RFC seems more clear about this.

According to 
https://tools.ietf.org/html/rfc2812#section-3.7.2

   Command: PING
   Parameters: <server1> [<server2>]

I read the argument of the ping from the server is not optional.
Please check.

**Comment by slingamn** [comment]
Correct, PING always requires at least one parameter.

Just to be clear, the presence of a parameter does not necessarily require the use of a trailing colon, e.g., the example of  `PING tolsun.oulu.fi` in the section you linked. This is only required when the parameter contains a space or begins with a colon.

**Comment by dinoex** [comment]
Sorry for the delay. After some reviews with IRC ops the fix is committed.
https://github.com/dinoex/iroffer-dinoex/commit/b0c56d5d7238fe9668b0efb572c68a56c50358b4
